### ISSUE TITLE
No Response By API When Clicking Pay Bubble

### ISSUE THREAD

**Issue by Ethan777100** [TelegramWeb/web.telegram.org#1]
No response when clicking the Pay bubble

![image](https://user-images.githubusercontent.com/49090166/99787474-c067a100-2b5a-11eb-847b-6e960e097b2d.png)

**Comment by ParveenBhadooOfficial** [comment]
This project is to bypass limits on web.telegram.org due to blocks, the updates and features are updated when they're available at web.telegram.org itself. This feature is currently not supported and you're supposed to use App to use it.
