### ISSUE TITLE
web.telegram.ind.in blocked on JioFiber

### ISSUE THREAD

**Issue by adir6** [TelegramWeb/web.telegram.org#2]
Hello, web.telegram.ind.in is getting randomly blocked by JioFiber now. I have to use VPN/Proxy to access the Telegram using web.telegram.ind.in now.

Error: Waiting for network...

**Comment by adir6** [comment]
> https://pluto.web.telegram.ind.in
> https://venus.web.telegram.ind.in
> https://aurora.web.telegram.ind.in
> https://vesta.web.telegram.ind.in
> https://flora.web.telegram.ind.in
> 
> Please try these URLs and let me know if they open using JioFiber.
> 
> They should show a webpage saying "403 Forbidden".

Hi, Yes all of them are loading fine for me on JioFiber. But yet, I am irregularly having "Waiting for Network..." from last few days.

**Comment by ParveenBhadooOfficial** [comment]
@adir6 try now in incognito mode.
